# Generated by Django 5.0 on 2025-11-12 10:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('program', models.CharField(choices=[('PNRR', 'PNRR'), ('FESR', 'FESR'), ('FSE', 'FSE'), ('ERASMUS', 'Erasmus+'), ('ALTRO', 'Altro')], default='PNRR', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cup', models.CharField(blank=True, max_length=32, null=True)),
                ('cig', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('ACTIVE', 'In corso'), ('CLOSED', 'Chiuso')], default='ACTIVE', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('MATERIALS', 'Materiali'), ('SERVICES', 'Servizi'), ('TRAINING', 'Formazione'), ('OTHER', 'Altro')], default='OTHER', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.school'),
        ),
        migrations.CreateModel(
            name='SpendingLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATERIALS', 'Materiali'), ('SERVICES', 'Servizi'), ('TRAINING', 'Formazione'), ('OTHER', 'Altro')], max_length=32)),
                ('base', models.CharField(choices=[('BUDGET', 'Budget'), ('SPENT', 'Speso attuale'), ('REMAINING', 'Residuo')], default='BUDGET', max_length=16)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentuale, es. 20 = 20%', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='projects.project')),
            ],
            options={
                'ordering': ['category', 'base', 'id'],
                'unique_together': {('project', 'category', 'base')},
            },
        ),
    ]
