# Generated by Django 5.0 on 2025-11-11 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vendor', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ATTREZZATURE', 'Attrezzature'), ('SERVIZI', 'Servizi'), ('FORMAZIONE', 'Formazione'), ('ALTRO', 'Altro')], default='ALTRO', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('doc_no', models.CharField(blank=True, max_length=100, verbose_name='Documento (n°/ID)')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
