# Generated by Django 5.0 on 2025-11-14 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Oggetto / titolo della delega', max_length=200)),
                ('scope', models.TextField(blank=True, help_text="Descrizione dell'ambito (es. gestione acquisti PNRR).", null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Progetto specifico collegato alla delega (facoltativo).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('school', models.ForeignKey(blank=True, help_text='Scuola a cui si riferisce la delega (facoltativa).', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.school')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
