# Generated by Django 5.0 on 2025-11-11 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='doc_no',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='school',
            name='codice_meccanografico',
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='document_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('MATERIALI', 'Materiali'), ('SERVIZI', 'Servizi'), ('FORMAZIONE', 'Formazione'), ('ALTRO', 'Altro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='project',
            name='cig',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='cup',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.CharField(choices=[('PNRR', 'PNRR'), ('FESR', 'FESR'), ('FSE', 'FSE'), ('ERASMUS', 'Erasmus+')], default='PNRR', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.school'),
        ),
        migrations.AlterField(
            model_name='project',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bozza'), ('ACTIVE', 'In corso'), ('CLOSED', 'Chiuso')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='SpendingLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATERIALI', 'Materiali'), ('SERVIZI', 'Servizi'), ('FORMAZIONE', 'Formazione'), ('ALTRO', 'Altro')], max_length=30)),
                ('percent', models.DecimalField(decimal_places=2, help_text='Percentuale (es. 20 = 20%)', max_digits=5)),
                ('basis', models.CharField(choices=[('BUDGET', 'Percento del budget'), ('SPENT', 'Percento del totale speso')], default='SPENT', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'category', 'basis')},
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
