# Generated by Django 5.0 on 2025-11-18 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_document_options_remove_document_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='school',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='to_user',
        ),
        migrations.AddField(
            model_name='delegation',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delegation',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='role_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ruolo delegato'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Attiva'), ('REVOKED', 'Revocata')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='projects.project'),
        ),
    ]
