# Generated by Django 5.0 on 2025-11-11 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_expense_options_alter_spendinglimit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spendinglimit',
            options={},
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='base',
            field=models.CharField(choices=[('BUDGET', 'Budget allocato'), ('SPENT', 'Spesa attuale')], default='BUDGET', max_length=12),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='category',
            field=models.CharField(choices=[('MATERIALI', 'Materiali'), ('FORMAZIONE', 'Formazione'), ('SERVIZI', 'Servizi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
