# Generated by Django 5.0 on 2025-11-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_delegation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In attesa di conferma'), ('ACTIVE', 'Attiva'), ('CONFIRMED', 'Confermata'), ('REVOKED', 'Revocata'), ('REJECTED', 'Rifiutata')], default='PENDING', max_length=16),
        ),
        migrations.CreateModel(
            name='CallForProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo bando')),
                ('program', models.CharField(choices=[('PNRR', 'PNRR'), ('FESR', 'FESR'), ('FSE', 'FSE'), ('ERASMUS', 'Erasmus+'), ('ALTRO', 'Altro')], default='PNRR', max_length=16, verbose_name='Programma')),
                ('internal_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice interno / riferimento')),
                ('source_name', models.CharField(help_text='Es. MIM, Regione, Agenzia Erasmus+, Fondazione...', max_length=100, verbose_name='Fonte')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Link al bando ufficiale')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Data pubblicazione')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='Scadenza')),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza interna'), ('OPEN', 'Aperto'), ('IN_PREP', 'In preparazione progetto'), ('CLOSED', 'Scaduto'), ('FUNDED', 'Finanziato'), ('NOT_FUNDED', 'Non finanziato')], default='OPEN', max_length=12, verbose_name='Stato')),
                ('amount_available', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Importo disponibile (se noto)')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Sintesi')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Requisiti principali')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Note interne')),
                ('import_source', models.CharField(choices=[('MANUAL', 'Inserimento manuale'), ('CSV', 'Import da file'), ('EMAIL', 'Da email / newsletter'), ('API', 'Sincronizzato da API esterna')], default='MANUAL', max_length=10, verbose_name='Origine dati')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Inserito il')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.school')),
            ],
            options={
                'verbose_name': 'Bando',
                'verbose_name_plural': 'Bandi',
                'ordering': ['-deadline_date', 'title'],
            },
        ),
    ]
