# Generated by Django 5.0 on 2025-11-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_fix_spendinglimit_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spendinglimit',
            options={'ordering': ['project_id', 'category', 'base', '-id']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MATERIALI', 'Materiali'), ('SERVIZI', 'Servizi'), ('FORMAZIONE', 'Formazione'), ('ALTRO', 'Altro')], default='ALTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='cig',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='cup',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.CharField(choices=[('PNRR', 'PNRR'), ('FESR', 'FESR'), ('FSE', 'FSE'), ('ERASMUS', 'Erasmus+'), ('ALTRO', 'Altro')], default='ALTRO', max_length=16),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='category',
            field=models.CharField(choices=[('MATERIALI', 'Materiali'), ('SERVIZI', 'Servizi'), ('FORMAZIONE', 'Formazione'), ('ALTRO', 'Altro')], default='ALTRO', max_length=20),
        ),
    ]
