# Generated by Django 5.0 on 2025-11-12 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_spendinglimit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spendinglimit',
            options={'ordering': ['category', 'basis', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='spendinglimit',
            unique_together={('project', 'category', 'basis')},
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spendinglimit',
            name='basis',
            field=models.CharField(choices=[('TOTAL_SPENT', 'Percentuale sul totale speso'), ('TOTAL_BUDGET', 'Percentuale sul budget totale')], default='TOTAL_SPENT', max_length=20),
        ),
        migrations.AddField(
            model_name='spendinglimit',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cig',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.CharField(choices=[('PNRR', 'PNRR'), ('FESR', 'FESR'), ('FSE', 'FSE'), ('ERASMUS', 'Erasmus+'), ('ALTRO', 'Altro')], default='PNRR', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='category',
            field=models.CharField(choices=[('MATERIALI', 'Materiali'), ('SERVIZI', 'Servizi'), ('FORMAZIONE', 'Formazione'), ('ALTRO', 'Altro')], default='MATERIALI', max_length=20),
        ),
        migrations.AlterField(
            model_name='spendinglimit',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Percentuale, es. 20 = 20%', max_digits=5),
        ),
        migrations.RemoveField(
            model_name='spendinglimit',
            name='base',
        ),
    ]
