# Generated by Django 5.0 on 2025-11-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.delegation'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In attesa di conferma'), ('ACTIVE', 'Attiva'), ('CONFIRMED', 'Accettata dal delegato'), ('REVOKED', 'Revocata'), ('REJECTED', 'Rifiutata')], default='PENDING', max_length=16),
        ),
    ]
