# Generated by Django 5.0 on 2025-11-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_notification_delegation_alter_delegation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In attesa di conferma'), ('ACTIVE', 'Attiva'), ('CONFIRMED', 'Confermata'), ('REVOKED', 'Revocata'), ('REJECTED', 'Rifiutata')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
