# Generated by Django 5.0 on 2025-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_delegation_status_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In attesa di conferma'), ('CONFIRMED', 'Confermata'), ('REJECTED', 'Rifiutata')], default='PENDING', max_length=16),
        ),
    ]
