# Generated by Django 5.0 on 2025-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_delegation_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='role_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruolo delegato'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In attesa di conferma'), ('CONFIRMED', 'Confermata'), ('REJECTED', 'Rifiutata'), ('REVOKED', 'Revocata')], default='PENDING', max_length=16),
        ),
    ]
