# Generated by Django 5.0 on 2025-11-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_delegation_note_alter_delegation_role_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Milestone')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('due_date', models.DateField(verbose_name='Data di Scadenza')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('COMPLETED', 'Completata'), ('DELAYED', 'In ritardo'), ('CANCELED', 'Annullata')], default='PENDING', max_length=10, verbose_name='Stato')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Data di Completamento')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Progetto')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestone',
                'ordering': ['due_date'],
            },
        ),
    ]
