# Generated by Django 5.0 on 2025-12-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Categoria')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Codice Unico (es. MATER)')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='projects.school')),
            ],
            options={
                'verbose_name': 'Categoria di Spesa',
                'verbose_name_plural': 'Categorie di Spesa',
            },
        ),
    ]
