# Generated by Django 5.0 on 2025-12-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_expensecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MATERIALS', 'Materiali'), ('SERVICES', 'Servizi'), ('TRAINING', 'Formazione'), ('OTHER', 'Altro'), ('DOTAZIONI DIGITALI', 'Dotazioni digitali'), ('ARREDI', 'Arredi'), ('INTERVENTI EDILIZI', 'Interventi edilizi')], default='OTHER', max_length=32),
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
